@echo off
echo ========================================
echo   Load Data to Snowflake
echo ========================================
echo.
echo This script will load JSON data files generated by the
echo enhanced e-commerce analytics app into Snowflake.
echo.
echo 📁 Data Sources:
echo   • JSON files from data/processed/ directory
echo   • Generated by the enhanced analytics pipeline
echo.
echo 🎯 Loading Process:
echo   1. Connect to Snowflake
echo   2. Load JSON files into RAW_EVENTS table
echo   3. Process raw events into structured tables
echo   4. Archive processed files
echo   5. Display loading statistics
echo.
echo 📊 Target Tables:
echo   • RAW_DATA.RAW_EVENTS (all events)
echo   • PROCESSED_DATA.PAGE_VIEWS
echo   • PROCESSED_DATA.PRODUCT_INTERACTIONS
echo   • PROCESSED_DATA.PURCHASES
echo   • PROCESSED_DATA.SEARCHES
echo   • PROCESSED_DATA.USER_ENGAGEMENT
echo.
echo ⚠️  Prerequisites:
echo   • Snowflake setup completed (run setup_snowflake.bat first)
echo   • Valid credentials in snowflake_config.json
echo   • JSON data files in data/processed/ directory
echo.
pause

echo.
echo 🚀 Starting data loading to Snowflake...
echo.

call kafka_venv\Scripts\activate.bat
python snowflake_loader.py

echo.
echo Loading completed! Check the output above for statistics.
echo.
pause